name: orix_pet
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.10.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  get: ^3.16.0
  flutter_svg: ^0.19.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: Mulish
      fonts:
        - asset: assets\fonts\Mulish-Regular.ttf
        - asset: assets\fonts\Mulish-Bold.ttf
          weight: 700
        - asset: assets\fonts\Mulish-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Mulish-Medium.ttf
          weight: 500
